# Generated by Django 5.0.7 on 2024-09-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmes',
            old_name='repete_event',
            new_name='repete_event_month',
        ),
        migrations.AlterField(
            model_name='programmes',
            name='day_of_weeks',
            field=models.ManyToManyField(blank=True, to='church_app.dayofweek'),
        ),
    ]
