# Generated by Django 5.0.7 on 2024-09-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0002_rename_repete_event_programmes_repete_event_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmes',
            name='deadline_repet_event',
            field=models.CharField(blank=True, choices=[('Toujours', 'Toujours'), ('until', "jusqu'à une certaine date")], max_length=255, null=True),
        ),
    ]
