# Generated by Django 5.0.7 on 2024-09-05 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0003_programmes_deadline_repet_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmes',
            old_name='begin_time_of_day',
            new_name='begin_time',
        ),
        migrations.RenameField(
            model_name='programmes',
            old_name='end_time_of_day',
            new_name='end_time',
        ),
    ]
