# Generated by Django 5.0.7 on 2024-09-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0005_alter_programmes_repete_event_month_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='type_notif',
            field=models.CharField(choices=[('programme', 'Programme'), ('annonce', 'Annonce')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
