# Generated by Django 5.0.7 on 2024-09-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0006_notifications_type_notif'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiches',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='affiches',
            name='is_view',
            field=models.BooleanField(default=True),
        ),
    ]
