# Generated by Django 5.0.7 on 2024-09-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0007_affiches_date_added_affiches_is_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='is_view',
            field=models.BooleanField(default=True),
        ),
    ]
