# Generated by Django 5.0.7 on 2024-09-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_app', '0008_annonces_is_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='day_time',
        ),
        migrations.AddField(
            model_name='annonces',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annonces',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
