# Generated by Django 5.0.7 on 2024-10-08 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_profile', to='auth.group'),
        ),
    ]
